<?xml version="1.0" encoding="utf-8"?><Database Name="SenseNetContentRepository" EntityNamespace="SenseNet.Search.Indexing" ContextNamespace="SenseNet.Search.Indexing" Class="IndexingTasksDataContext" Modifier="Abstract" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=SenseNetContentRepository;Integrated Security=True" SettingsObjectName="SenseNet.ContentRepository.Properties.Settings" SettingsPropertyName="SenseNetContentRepositoryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IndexingActivity" Member="IndexingActivities">
    <Type Name="IndexingActivity">
      <Column Name="IndexingActivityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActivityType" Type="IndexingActivityType" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NodeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VersionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SingleVersion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MoveOrRename" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsLastDraftValue" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="VersionTimestamp" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Hash" Type="System.Data.Linq.Binary" DbType="VarBinary(50)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>